# Use Node.js image
FROM node:18

# Install Python, pip, and ffmpeg
RUN apt-get update && \
    apt-get install -y python3 python3-pip ffmpeg && \
    apt-get clean

# Set working directory
WORKDIR /app

# Copy backend files
COPY backend ./backend

# Go into backend folder
WORKDIR /app/backend

# Install Node dependencies
RUN npm install

# Install Python dependencies
COPY backend/requirements.txt ../requirements.txt
RUN pip3 install -r ../requirements.txt

# Expose port
EXPOSE 10000

# Start the app
CMD ["npm", "start"]
